### ISSUE TITLE
GLUE Batch Effect Removal

### ISSUE THREAD

**Issue by valentinwust** [ChaozhongLiu/MinNet#2]
In Fig.3 A and B you show pictures where GLUE doesn't properly remove batch effects. However, when I try to reproduce this with the same data the batch effect removal seems to works fine. Are you sure you have told GLUE the batch labels? I can't find the code for the model that was trained for Fig.3 A, but for example [in this code for Fig.2](https://github.com/ChaozhongLiu/MinNet/blob/master/fig2/BMMC_data/GLUE/glue.py) GLUE doesn't actually get the batch labels. As explained in [their tutorial](https://scglue.readthedocs.io/en/latest/training.html), this requires adding `use_batch`, like:

```python
`scglue.models.configure_dataset(
    rna, "NB", use_highly_variable=True,
    use_layer="raw", use_rep="X_pca",
    use_batch="batch" # This does the batch effect removal
)
```

**Comment by ChaozhongLiu** [comment]
Hi,

Thanks for raising this up! First of all, I believe this is due to the update in GLUE.
I followed the same website tutorial at the time when doing the benchmark, and I'm quite sure that the batch function doesn't exit at that time (early 2022).

I'm a big fan of GLUE and I'm excited to see it can do batch correction now (as I trust your results)

Let me know if you have any concerns!

Best,
Chaozhong

**Comment by valentinwust** [comment]
Interesting, looks like you are right; I hadn't looked at the development history of GLUE. Batch correction made it into the [final paper](https://www.nature.com/articles/s41587-022-01284-4) so I assumed this was always implemented, but it is indeed missing from [the preprint](https://www.biorxiv.org/content/10.1101/2021.08.22.457275v2).
